const PersonnesAout = [
  { numero: 1, nom: 'Benjamin', jour: 'Sunday' },
  { numero: 2, nom: 'Gaston', jour: 'Monday' },
  { numero: 3, nom: 'Marie', jour: 'Tuesday' },
  { numero: 4, nom: 'Lucie', jour: 'Wednesday' },
  { numero: 5, nom: 'Charles', jour: 'Thursday' },
  { numero: 6, nom: 'Pierre', jour: 'Friday' },
  { numero: 7, nom: 'François', jour: 'Saturday' },
  { numero: 8, nom: 'Sophie', jour: 'Sunday' },
  { numero: 9, nom: 'Étienne', jour: 'Monday' },
  { numero: 10, nom: 'Claire', jour: 'Tuesday' },
  { numero: 11, nom: 'Anne', jour: 'Wednesday' },
  { numero: 12, nom: 'Léa', jour: 'Thursday' },
  { numero: 13, nom: 'Julie', jour: 'Friday' },
  { numero: 14, nom: 'Antoine', jour: 'Saturday' },
  { numero: 15, nom: 'Philippe', jour: 'Sunday' },
  { numero: 16, nom: 'Nathalie', jour: 'Monday' },
  { numero: 17, nom: 'Martin', jour: 'Tuesday' },
  { numero: 18, nom: 'Thomas', jour: 'Wednesday' },
  { numero: 19, nom: 'Céline', jour: 'Thursday' },
  { numero: 20, nom: 'Louise', jour: 'Friday' },
  { numero: 21, nom: 'Paul', jour: 'Saturday' },
  { numero: 22, nom: 'Jean', jour: 'Sunday' },
  { numero: 23, nom: 'Mireille', jour: 'Monday' },
  { numero: 24, nom: 'Hélène', jour: 'Tuesday' },
  { numero: 25, nom: 'Lise', jour: 'Wednesday' },
  { numero: 26, nom: 'Vincent', jour: 'Thursday' },
  { numero: 27, nom: 'David', jour: 'Friday' },
  { numero: 28, nom: 'Élisabeth', jour: 'Saturday' },
  { numero: 29, nom: 'Caroline', jour: 'Sunday' },
  { numero: 30, nom: 'Nicolas', jour: 'Monday' },
  { numero: 31, nom: 'Jacques', jour: 'Tuesday' },
  { numero: 32, nom: 'Renée', jour: 'Wednesday' }
];

export default PersonnesAout;
