const PersonnesMai = [
  { numero: 1, nom: "Shwìì tɑ̄ nkwēn", jour: "Wednesday" },
  { numero: 2, nom: "Shwínā", jour: "Thursday" },
  { numero: 3, nom: "Shwī nā ò", jour: "Friday" },
  { numero: 4, nom: "Sìdīēmbwèn", jour: "Saturday" },
  { numero: 5, nom: "Sìpīēndɑ̀h", jour: "Sunday" },
  { numero: 6, nom: "Sipūānkhù", jour: "Sunday" },
  { numero: 7, nom: "Sòm Mbūànì", jour: "Monday" },
  { numero: 8, nom: "Tā'sī ā lɑ́", jour: "Tuesday" },
  { numero: 9, nom: "Tâ'sǐ pè' / pə̀'", jour: "Wednesday" },
  { numero: 10, nom: "Títìānì", jour: "Thursday" },
  { numero: 11, nom: "Tómnshì", jour: "Friday" },
  { numero: 12, nom: "Tómnshǐ Nkwè'nì", jour: "Saturday" },
  { numero: 13, nom: "Tómnshǐvɑ̀h", jour: "Sunday" },
  { numero: 14, nom: "Tʉ̄ɑ̄' mbō nkō", jour: "Monday" },
  { numero: 15, nom: "Tûmbhì", jour: "Tuesday" },
  { numero: 16, nom: "Vɑ̀h zǎ", jour: "Wednesday" },
  { numero: 17, nom: "Vɑ̀h Sʉ̀sʉ̀ɑ̀", jour: "Thursday" },
  { numero: 18, nom: "Wěnsìnēēsī", jour: "Friday" },
  { numero: 19, nom: "Wěnsìpūānkhù", jour: "Saturday" },
  { numero: 20, nom: "Wū sì lò'", jour: "Sunday" },
  { numero: 21, nom: "Wū sì mbìà", jour: "Monday" },
  { numero: 22, nom: "Yà Póngʉ̀'", jour: "Tuesday" },
  { numero: 23, nom: "Yà Túnù", jour: "Wednesday" },
  { numero: 24, nom: "Yā' kwà'", jour: "Thursday" },
  { numero: 25, nom: "Yām", jour: "Friday" },
  { numero: 26, nom: "Yòmɑ̀ / Yə̀bɑ̀", jour: "Saturday" },
  { numero: 27, nom: "Yōmnā ō ngʉ́", jour: "Sunday" },
  { numero: 28, nom: "Yōpnā ō", jour: "Monday" },
  { numero: 29, nom: "Yō'sì", jour: "Tuesday" },
  { numero: 30, nom: "Yū'nì", jour: "Wednesday" },
  { numero: 31, nom: "Zɑ́h nàm / Zɑ́h nàp", jour: "Thursday" },
  { numero: 32, nom: "Zén fʉ̀'", jour: "Friday" }
];

export default PersonnesMai;
