const PersonnesAvril = [
  { numero: 1, nom: "Ntōòvɑ̀h", jour: "Saturday"  },
  { numero: 2, nom: "Ntʉ̄ɑ̄'mbō lɑ̀' sə̄ə̄ wū" , jour: "Sunday" },
  { numero: 3, nom: "Ntúmbó nkɑ̄ɑ̄" , jour: "Monday" },
  { numero: 4, nom: "Nǔlɑ̄'", jour: "Tuesday"  },
  { numero: 5, nom: "Nù lɑ̀' pə̄h wèn ntìā", jour: "Wednesday"  },
  { numero: 6, nom: "Nù pɑ́' mbə̄h wèn" , jour: "Thursday" },
  { numero: 7, nom: "Nzɑ́ lēē" , jour: "Friday" },
  { numero: 8, nom: "Nzhînù" , jour: "Saturday" },
  { numero: 9, nom: "Nzhînùwèn" , jour: "Sunday" },
  { numero: 10, nom: "Ǒ sì ghé'" , jour: "Monday" },
  { numero: 11, nom: "Ǒ sì nēēsī" , jour: "Tuesday" },
  { numero: 12, nom: "Ǒ sì pēn" , jour: "Wednesday" },
  { numero: 13, nom: "Ǒ sì pōh" , jour: "Thursday" },
  { numero: 14, nom: "Pə̄h nùsìpè'" , jour: "Friday" },
  { numero: 15, nom: "Pè'nì" , jour: "Saturday" },
  { numero: 16, nom: "Pénthʉ̄" , jour: "Sunday" },
  { numero: 17, nom: "Pě'sī / Pə̌'sī" , jour: "Monday" },
  { numero: 18, nom: "Pě'zīī / Pə̌'zīī", jour: "Tuesday"  },
  { numero: 19, nom: "Phì tɑ̄ nkɑ̄ɑ̄" , jour: "Wednesday" },
  { numero: 20, nom: "Phǐ nkwè'nì" , jour: "Thursday" },
  { numero: 21, nom: "Pìī nkwè'nì", jour: "Friday"  },
  { numero: 22, nom: "Pɑ̄h nù" , jour: "Saturday" },
  { numero: 23, nom: "Pōh nùsìpè'" , jour: "Sunday" },
  { numero: 24, nom: "Pó ngʉ̀'", jour: "Monday"  },
  { numero: 25, nom: "Sà'" , jour: "Tuesday" },
  { numero: 26, nom: "Sǎ'lòh" , jour: "Wednesday" },
  { numero: 27, nom: "Sǎ'lòh zǎ" , jour: "Thursday" },
  { numero: 28, nom: "Sǎ' Mbūànì" , jour: "Friday" },
  { numero: 29, nom: "Sǎ' Nkwè'nì" , jour: "Saturday" },
  { numero: 30, nom: "Sǎ' Nzhì", jour: "Sunday"  },
  { numero: 31, nom: "Sǎ' pūh", jour: "Monday"  },
  { numero: 32, nom: "Sǎ' zhínù" , jour: "Tuesday" }
];

export default PersonnesAvril;
