const personnesFevrier = [
  { numero: 1, nom: 'Làmsí nshù', jour: 'Thursday' },
  { numero: 2, nom: 'Lə̌hmbhì', jour: 'Friday' },
  { numero: 3, nom: 'Lǒnàm', jour: 'Saturday' },
  { numero: 4, nom: 'Lǒsīē', jour: 'Sunday' },
  { numero: 5, nom: 'Lǒsīē nnák', jour: 'Monday' },
  { numero: 6, nom: 'Mɑ̂fʉ̀ / Mɑ̂fə̀', jour: 'Tuesday' },
  { numero: 7, nom: 'Mɑ̂fʉ̀ / Mɑ̂fə̀ Mbūànì', jour: 'Wednesday' },
  { numero: 8, nom: "Mɑ̂fʉ̀ / Mɑ̂fə̀ nkō'", jour: 'Thursday' },
  { numero: 9, nom: "Mɑ̄ngátnzhʉ̀'", jour: 'Friday' },
  { numero: 10, nom: "Mbè' Cwè'", jour: 'Saturday' },
  { numero: 11, nom: "Mbè' Nɑ̄h", jour: 'Sunday' },
  { numero: 12, nom: "Mbè'zīī", jour: "Monday" },
  { numero: 13, nom: "Mbó Fʉ̀'", jour: "Tuesday" },
  { numero: 14, nom: "Mbūànì", jour: "Wednesday" },
  { numero: 15, nom: "Mbūànì Wèn", jour: "Thursday" },
  { numero: 16, nom: "Mênfʉ̀ / Mênfə̀", jour: "Friday" },
  { numero: 17, nom: "Mênkām", jour: "Saturday" },
  { numero: 18, nom: "Mfɑ̀'ndīēkò", jour: "Sunday" },
  { numero: 19, nom: "Nɑ́h nkwè'nì / Nɑ́h nkə̀'nì", jour: "Monday" },
  { numero: 20, nom: "Nɑ́h vɑ̀h", jour: "Tuesday" },
  { numero: 21, nom: "Nàm", jour: "Wednesday" },
  { numero: 22, nom: "Nàm à", jour: "Thursday" },
  { numero: 23, nom: "Ncǎ' miè", jour: "Friday" },
  { numero: 24, nom: "Laure", jour: "Saturday" },
  { numero: 25, nom: "Damien", jour: "Sunday" },
  { numero: 26, nom: "Charlotte", jour: "Monday" },
  { numero: 27, nom: "Alexandre", jour: "Tuesday" },
  { numero: 28, nom: "Aline", jour: "Wednesday" },
  { numero: 29, nom: "Hélène", jour: "Thursday" },
  { numero: 30, nom: "Guillaume", jour: "Friday" },
  { numero: 31, nom: "Chloé", jour: "Saturday" },
  { numero: 32, nom: "Jacques", jour: "Sunday" }
];

export default personnesFevrier;
