const personnesMars = [
    { numero: 1, nom: 'Jean' },
    { numero: 2, nom: 'Sophie' },
    { numero: 3, nom: 'Pierre' },
    { numero: 4, nom: 'Marie' },
    { numero: 5, nom: 'Luc' },
    { numero: 6, nom: 'Julie' },
    { numero: 7, nom: 'Antoine' },
    { numero: 8, nom: 'Céline' },
    { numero: 9, nom: 'François' },
    { numero: 10, nom: 'Aurélie' },
    { numero: 11, nom: 'Thomas' },
    { numero: 12, nom: 'Valérie' },
    { numero: 13, nom: 'Charles' },
    { numero: 14, nom: 'Caroline' },
    { numero: 15, nom: 'Louis' },
    { numero: 16, nom: 'Hélène' },
    { numero: 17, nom: 'Guillaume' },
    { numero: 18, nom: 'Chloé' },
    { numero: 19, nom: 'Jacques' },
    { numero: 20, nom: 'Elodie' },
    { numero: 21, nom: 'Philippe' },
    { numero: 22, nom: 'Anne' },
    { numero: 23, nom: 'Nicolas' },
    { numero: 24, nom: 'Laure' },
    { numero: 25, nom: 'Damien' },
    { numero: 26, nom: 'Charlotte' },
    { numero: 27, nom: 'Alexandre' },
    { numero: 28, nom: 'Aline' },
    { numero: 29, nom: 'Caroline' },
    { numero: 30, nom: 'Nicolas' },
    { numero: 31, nom: 'Jacques' },
    { numero: 32, nom: 'Renée' }
  ];
  
  export default personnesMars;
  