const personnesMars = [
    { numero: 1, nom: 'Jean', jour: 'Monday'  },
    { numero: 2, nom: 'Sophie' , jour: 'Tuesday' },
    { numero: 3, nom: 'Pierre' , jour: 'Wednesday' },
    { numero: 4, nom: 'Marie' , jour: 'Thursday' },
    { numero: 5, nom: 'Luc' , jour: 'Friday' },
    { numero: 6, nom: 'Julie' , jour: 'Saturday' },
    { numero: 7, nom: 'Antoine' , jour: 'Sunday' },
    { numero: 8, nom: 'Céline' , jour: 'Monday' },
    { numero: 9, nom: 'François' , jour: 'Tuesday' },
    { numero: 10, nom: 'Aurélie' , jour: 'Wednesday' },
    { numero: 11, nom: 'Thomas' , jour: 'Thursday' },
    { numero: 12, nom: 'Valérie' , jour: 'Friday' },
    { numero: 13, nom: 'Charles' , jour: 'Saturday' },
    { numero: 14, nom: 'Caroline' , jour: 'Sunday' },
    { numero: 15, nom: 'Louis' , jour: 'Monday' },
    { numero: 16, nom: 'Hélène' , jour: 'Tuesday' },
    { numero: 17, nom: 'Guillaume', jour: 'Wedneday'  },
    { numero: 18, nom: 'Chloé' , jour: 'Thursday' },
    { numero: 19, nom: 'Jacques' , jour: 'Friday' },
    { numero: 20, nom: 'Elodie' , jour: 'Saturday' },
    { numero: 21, nom: 'Philippe' , jour: 'Sunday' },
    { numero: 22, nom: 'Anne-Sophie', jour: 'Monday'  },
    { numero: 23, nom: 'Nicolas' , jour: 'Tuesday' },
    { numero: 24, nom: 'Laure' , jour: 'Wednesday' },
    { numero: 25, nom: 'Damien' , jour: 'Friday' },
    { numero: 26, nom: 'Charlotte' , jour: 'Saturday' },
    { numero: 27, nom: 'Alexandre' , jour: 'Sunday' },
    { numero: 28, nom: 'Aline' , jour: 'Monday' },
    { numero: 29, nom: 'Caroline', jour: 'Tuesday'  },
    { numero: 30, nom: 'Nicolas' , jour: 'Wednesday' },
    { numero: 31, nom: 'Jacques' , jour: 'Thursday' },
    { numero: 32, nom: 'Renée', jour: 'Friday'  }
  ];
  
  export default personnesMars;
  