const PersonnesJuin = [
  { numero: 1, nom: 'Jean', jour: 'Saturday' },
  { numero: 2, nom: 'Sophie', jour: 'Sunday' },
  { numero: 3, nom: 'Pierre', jour: 'Monday' },
  { numero: 4, nom: 'Marie', jour: 'Tuesday' },
  { numero: 5, nom: 'Luc', jour: 'Wednesday' },
  { numero: 6, nom: 'Julie', jour: 'Thursday' },
  { numero: 7, nom: 'Antoine', jour: 'Friday' },
  { numero: 8, nom: 'Céline', jour: 'Saturday' },
  { numero: 9, nom: 'François', jour: 'Sunday' },
  { numero: 10, nom: 'Aurélie', jour: 'Monday' },
  { numero: 11, nom: 'Thomas', jour: 'Tuesday' },
  { numero: 12, nom: 'Valérie', jour: 'Wednesday' },
  { numero: 13, nom: 'Charles', jour: 'Thursday' },
  { numero: 14, nom: 'Caroline', jour: 'Friday' },
  { numero: 15, nom: 'Louis', jour: 'Saturday' },
  { numero: 16, nom: 'Hélène', jour: 'Sunday' },
  { numero: 17, nom: 'Guillaume', jour: 'Monday' },
  { numero: 18, nom: 'Chloé', jour: 'Tuesday' },
  { numero: 19, nom: 'Jacques', jour: 'Wednesday' },
  { numero: 20, nom: 'Elodie', jour: 'Thursday' },
  { numero: 21, nom: 'Philippe', jour: 'Friday' },
  { numero: 22, nom: 'Anne', jour: 'Saturday' },
  { numero: 23, nom: 'Nicolas', jour: 'Sunday' },
  { numero: 24, nom: 'Laure', jour: 'Monday' },
  { numero: 25, nom: 'Damien', jour: 'Tuesday' },
  { numero: 26, nom: 'Charlotte', jour: 'Wednesday' },
  { numero: 27, nom: 'Alexandre', jour: 'Thursday' },
  { numero: 28, nom: 'Aline', jour: 'Friday' },
  { numero: 29, nom: 'Hélène', jour: 'Saturday' },
  { numero: 30, nom: 'Guillaume', jour: 'Sunday' },
  { numero: 31, nom: 'Chloé', jour: 'Monday' },
  { numero: 32, nom: 'Jacques', jour: 'Tuesday' }
];

export default PersonnesJuin;
