const personnesJanvier = [
  { numero: 1, nom: "ɑ́ Yāā pípè'", jour: "Sunday" },
  { numero: 2, nom: "Bɑ̄ ntèn", jour: "Monday" },
  { numero: 3, nom: "Cǎk ndíndēē", jour: "Tuesday" },
  { numero: 4, nom: "Cǎk nkwè'nì / Cǎk nkə̀'nì", jour: "Wednesday" },
  { numero: 5, nom: "Cāk tɑ̄ Nzɑ̄", jour: "Thursday" },
  { numero: 6, nom: "Cǎk vɑ̀h", jour: "Friday" },
  { numero: 7, nom: "Cāp nā ò, Cām nā ò", jour: "Saturday" },
  { numero: 8, nom: "Cà'sì", jour: "Sunday" },
  { numero: 9, nom: "Cà'sì zǎ", jour: "Monday" },
  { numero: 10, nom: "Có'nzhì", jour: "Tuesday" },
  { numero: 11, nom: "Cwè'fī", jour: "Wednesday" },
  { numero: 12, nom: "Fɑ̀'sì pūā", jour: "Thursday" },
  { numero: 13, nom: "Fhʉ̄ sīē ndó", jour: "Friday" },
  { numero: 14, nom: "Fìènkàk", jour: "Saturday" },
  { numero: 15, nom: "Fʉ̀ / Fə̀", jour: "Sunday" },
  { numero: 16, nom: "Fʉ̀ mbūànì", jour: "Monday" },
  { numero: 17, nom: "Fʉ̀ nkō'", jour: "Tuesday" },
  { numero: 18, nom: "Fʉ̀'", jour: "Wednesday" },
  { numero: 19, nom: "Fʉ̌' sɑ̀'", jour: "Thursday" },
  { numero: 20, nom: "Fʉ̀' sì mìè", jour: "Friday" },
  { numero: 21, nom: "Fʉ̀' sì fōh", jour: "Saturday" },
  { numero: 22, nom: "Fʉ̀' zā", jour: "Sunday" },
  { numero: 23, nom: "Ghə̀ə̄ fʉ̀", jour: "Monday" },
  { numero: 24, nom: "Ghěn mbhì", jour: "Tuesday" },
  { numero: 25, nom: "Kàhmɑ̄ncò", jour: "Wednesday" },
  { numero: 26, nom: "Kèē nkù'nì", jour: "Thursday" },
  { numero: 27, nom: "Kèē nkwè'nì", jour: "Friday" },
  { numero: 28, nom: "Kèēvɑ̀h", jour: "Saturday" },
  { numero: 29, nom: "Kwǎ'nù", jour: "Sunday" },
  { numero: 30, nom: "Kwě'nàm", jour: "Monday" },
  { numero: 31, nom: "Lɑ́'fhʉ̀'", jour: "Tuesday" },
  { numero: 32, nom: "Lɑ́' mbūànì", jour: "Wednesday" }
];

export default personnesJanvier;
