const personnesJanvier = [
  { numero: 1, nom: 'Benjamin' },
  { numero: 2, nom: 'Gaston' },
  { numero: 3, nom: 'Marie' },
  { numero: 4, nom: 'Lucie' },
  { numero: 5, nom: 'Charles' },
  { numero: 6, nom: 'Pierre' },
  { numero: 7, nom: 'François' },
  { numero: 8, nom: 'Sophie' },
  { numero: 9, nom: 'Étienne' },
  { numero: 10, nom: 'Claire' },
  { numero: 11, nom: 'Anne' },
  { numero: 12, nom: 'Léa' },
  { numero: 13, nom: 'Julie' },
  { numero: 14, nom: 'Antoine' },
  { numero: 15, nom: 'Philippe' },
  { numero: 16, nom: 'Nathalie' },
  { numero: 17, nom: 'Martin' },
  { numero: 18, nom: 'Thomas' },
  { numero: 19, nom: 'Céline' },
  { numero: 20, nom: 'Louise' },
  { numero: 21, nom: 'Paul' },
  { numero: 22, nom: 'Jean' },
  { numero: 23, nom: 'Mireille' },
  { numero: 24, nom: 'Hélène' },
  { numero: 25, nom: 'Lise' },
  { numero: 26, nom: 'Vincent' },
  { numero: 27, nom: 'David' },
  { numero: 28, nom: 'Élisabeth' },
  { numero: 29, nom: 'Caroline' },
  { numero: 30, nom: 'Nicolas' },
  { numero: 31, nom: 'Jacques' },
  { numero: 32, nom: 'Renée' }
];

export default personnesJanvier;
