const PersonnesSeptembre = [
  { numero: 1, nom: "Sīēbɑ́ncə̄ə̄", jour: "Thursday" },
  { numero: 2, nom: "Síémbíwèn", jour: "Friday" },
  { numero: 3, nom: "Sīēkɑ̀'pēn", jour: "Saturday" },
  { numero: 4, nom: "Síépēn", jour: "Sunday" },
  { numero: 5, nom: "Sīèwèn", jour: "Monday" },
  { numero: 6, nom: "Síé yɑ̄ɑ̄ nzhì", jour: "Tuesday" },
  { numero: 7, nom: "Síéyú'", jour: "Wednesday" },
  { numero: 8, nom: "Tâlə̀ə̀", jour: "Thursday" },
  { numero: 9, nom: "Tâlòm", jour: "Friday" },
  { numero: 10, nom: "Ncà'mbōk", jour: "Saturday" },
  { numero: 11, nom: "Càm mɑ̄ mbè'", jour: "Sunday" },
  { numero: 12, nom: "Cátmɑ̄nì", jour: "Monday" },
  { numero: 13, nom: "Ca᷅mnà'", jour: "Tuesday" },
  { numero: 14, nom: "Cɑ́'wūɑ̄", jour: "Wednesday" },
  { numero: 15, nom: "Cwè' lɑ̀' hwīē", jour: "Thursday" },
  { numero: 16, nom: "Tūpòwèn", jour: "Friday" },
  { numero: 17, nom: "Ntéépīē", jour: "Saturday" },
  { numero: 18, nom: "Ntē' lɑ̀' lēē", jour: "Sunday" },
  { numero: 19, nom: "Ntû'kām", jour: "Monday" },
  { numero: 20, nom: "Ntò'kām", jour: "Tuesday" },
  { numero: 21, nom: "Ntò'wūɑ̄", jour: "Wednesday" },
  { numero: 22, nom: "Wààngɑ́ɑ́", jour: "Thursday" },
  { numero: 23, nom: "Wààntóó", jour: "Friday" },
  { numero: 24, nom: "Wèn lɑ̀' zhī", jour: "Saturday" },
  { numero: 25, nom: "Wèn lɑ̀' kwé'", jour: "Sunday" },
  { numero: 26, nom: "Wěnjīī", jour: "Monday" },
  { numero: 27, nom: "Wènlɑ̀'kwé'ngà'pèè", jour: "Tuesday" },
  { numero: 28, nom: "Wènlɑ̀'péé'ngà'pèè", jour: "Wednesday" },
  { numero: 29, nom: "Wènsìlɑ́hnjàm", jour: "Thursday" },
  { numero: 30, nom: "Wèntōmndʉ̄ɑ̄", jour: "Friday" },
  { numero: 31, nom: "Yīīnù", jour: "Saturday" },
  { numero: 32, nom: "Yīītɑ̄mbēn", jour: "Sunday" }
];

export default PersonnesSeptembre;
